# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evento_regras_violacoes.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'evento_regras_violacoes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65vento_regras_violacoes.proto\"\x86\x05\n\x15\x45ventoRegrasViolacoes\x12 \n\x18\x64ispositivo_numero_serie\x18\x01 \x02(\t\x12\x18\n\x10\x64\x61ta_hora_evento\x18\x02 \x02(\x03\x12;\n\x0eregrasVioladas\x18\x03 \x03(\x0b\x32#.EventoRegrasViolacoes.RegraViolada\x1a\xf3\x03\n\x0cRegraViolada\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04nome\x18\x02 \x02(\t\x12?\n\tcondicoes\x18\x03 \x03(\x0b\x32,.EventoRegrasViolacoes.RegraViolada.Condicao\x12\x43\n\x0f\x61lertasEnviados\x18\x04 \x03(\x0b\x32*.EventoRegrasViolacoes.RegraViolada.Alerta\x1a$\n\x08\x43ondicao\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04nome\x18\x02 \x02(\t\x1a\x9c\x02\n\x06\x41lerta\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x64\x65stino\x18\x02 \x02(\t\x12?\n\x05sleep\x18\x03 \x02(\x0e\x32\x30.EventoRegrasViolacoes.RegraViolada.Alerta.Sleep\x12\x13\n\x0b\x64\x65lay_sleep\x18\x04 \x01(\x05\x12\x44\n\x04tipo\x18\x05 \x02(\x0e\x32\x36.EventoRegrasViolacoes.RegraViolada.Alerta.TiposEnvios\".\n\x0bTiposEnvios\x12\x07\n\x03SMS\x10\x01\x12\t\n\x05\x45MAIL\x10\x02\x12\x0b\n\x07TWITTER\x10\x03\")\n\x05Sleep\x12\t\n\x05TEMPO\x10\x01\x12\t\n\x05UNICO\x10\x02\x12\n\n\x06SEMPRE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evento_regras_violacoes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTOREGRASVIOLACOES']._serialized_start=34
  _globals['_EVENTOREGRASVIOLACOES']._serialized_end=680
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA']._serialized_start=181
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA']._serialized_end=680
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_CONDICAO']._serialized_start=357
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_CONDICAO']._serialized_end=393
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA']._serialized_start=396
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA']._serialized_end=680
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA_TIPOSENVIOS']._serialized_start=591
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA_TIPOSENVIOS']._serialized_end=637
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA_SLEEP']._serialized_start=639
  _globals['_EVENTOREGRASVIOLACOES_REGRAVIOLADA_ALERTA_SLEEP']._serialized_end=680
# @@protoc_insertion_point(module_scope)
