# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_network.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import maxpb_report_pb2 as maxpb__report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13maxpb_network.proto\x1a\x12maxpb_report.proto\"E\n\x07Routing\x12\x1d\n\x0b\x66romNetwork\x18\x01 \x01(\x0e\x32\x08.Network\x12\x1b\n\ttoNetwork\x18@ \x01(\x0e\x32\x08.Network\"i\n\tRoutePack\x12\x10\n\x08\x64\x65viceID\x18\x01 \x02(\r\x12#\n\x12identificationPack\x18\x02 \x01(\x0b\x32\x07.IDPack\x12\x17\n\x05route\x18\x03 \x02(\x0b\x32\x08.Routing\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x0c*\xc2\x03\n\x07Network\x12\x0f\n\x0bN_BROADCAST\x10\x00\x12\r\n\tN_TRACKER\x10\x01\x12\x0c\n\x08N_RS485A\x10\x02\x12\x0c\n\x08N_RS485B\x10\x03\x12\x0c\n\x08N_RS232A\x10\x04\x12\x0c\n\x08N_RS232B\x10\x05\x12\n\n\x06N_WIFI\x10\x06\x12\x0e\n\nN_GSM_GPRS\x10\x07\x12\n\n\x06N_CAN1\x10\x08\x12\n\n\x06N_CAN2\x10\t\x12\t\n\x05N_USB\x10\n\x12\x0c\n\x08N_ZIGBEE\x10\x0b\x12\x0e\n\nN_LORA_P2P\x10\x0c\x12\x13\n\x0fN_SATELLITE_IDP\x10\r\x12\x0f\n\x0bN_SATELLITE\x10\x0e\x12\t\n\x05N_LUA\x10\x0f\x12\x0f\n\x0bN_BLUETOOTH\x10\x10\x12\t\n\x05N_UDP\x10\x11\x12\x0b\n\x07N_CLOUD\x10\x12\x12\x0e\n\nN_LORA_WAN\x10\x13\x12\x0e\n\nN_ETHERNET\x10\x14\x12\n\n\x06N_MQTT\x10\x15\x12\x0c\n\x08N_RFU_01\x10\x16\x12\x0c\n\x08N_RFU_02\x10\x17\x12\x0c\n\x08N_RFU_03\x10\x18\x12\x0c\n\x08N_RFU_04\x10\x19\x12\x0c\n\x08N_RFU_05\x10\x1a\x12\x0c\n\x08N_RFU_06\x10\x1b\x12\x0c\n\x08N_RFU_07\x10\x1c\x12\x0c\n\x08N_RFU_08\x10\x1d\x12\x0c\n\x08N_RFU_09\x10\x1e\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_NETWORK']._serialized_start=222
  _globals['_NETWORK']._serialized_end=672
  _globals['_ROUTING']._serialized_start=43
  _globals['_ROUTING']._serialized_end=112
  _globals['_ROUTEPACK']._serialized_start=114
  _globals['_ROUTEPACK']._serialized_end=219
# @@protoc_insertion_point(module_scope)
