# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_control_multimedia.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_control_multimedia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emaxpb_control_multimedia.proto\"\x82\x01\n\x18MultimediaServiceControl\x12!\n\x06\x41\x63tion\x18\x01 \x01(\x0e\x32\x11.MultimediaAction\x12\x0f\n\x07pathMSC\x18\x02 \x01(\t\x12\x10\n\x08listSize\x18\x03 \x01(\r\x12\r\n\x05index\x18\x04 \x01(\r\x12\x11\n\tDTMultiSC\x18\x05 \x02(\x04\".\n\x1eMultimediaServiceControlReturn\x12\x0c\n\x04list\x18\x01 \x03(\t*\xa4\x01\n\x10MultimediaAction\x12\x0b\n\x07MA_NONE\x10\x00\x12\n\n\x06MA_ADD\x10\x01\x12\x0c\n\x08MA_CLEAR\x10\x02\x12\x10\n\x0cMA_BUZZER_ON\x10\x03\x12\x11\n\rMA_BUZZER_OFF\x10\x04\x12\x0c\n\x08MA_RFU05\x10\x05\x12\x0c\n\x08MA_RFU06\x10\x06\x12\x0c\n\x08MA_RFU07\x10\x07\x12\x0c\n\x08MA_RFU08\x10\x08\x12\x0c\n\x08MA_RFU09\x10\tB#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_control_multimedia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_MULTIMEDIAACTION']._serialized_start=216
  _globals['_MULTIMEDIAACTION']._serialized_end=380
  _globals['_MULTIMEDIASERVICECONTROL']._serialized_start=35
  _globals['_MULTIMEDIASERVICECONTROL']._serialized_end=165
  _globals['_MULTIMEDIASERVICECONTROLRETURN']._serialized_start=167
  _globals['_MULTIMEDIASERVICECONTROLRETURN']._serialized_end=213
# @@protoc_insertion_point(module_scope)
