# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_satellite.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_satellite.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import maxpb_report_pb2 as maxpb__report__pb2
import maxpb_gpio_pb2 as maxpb__gpio__pb2
import maxpb_gps_pb2 as maxpb__gps__pb2
import maxpb_telemetry_pb2 as maxpb__telemetry__pb2
import maxpb_customer_data_pb2 as maxpb__customer__data__pb2
import maxpb_users_pb2 as maxpb__users__pb2
import maxpb_beacon_pb2 as maxpb__beacon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15maxpb_satellite.proto\x1a\x12maxpb_report.proto\x1a\x10maxpb_gpio.proto\x1a\x0fmaxpb_gps.proto\x1a\x15maxpb_telemetry.proto\x1a\x19maxpb_customer_data.proto\x1a\x11maxpb_users.proto\x1a\x12maxpb_beacon.proto\"\xf0\x03\n\rSatelliteData\x12\x10\n\x08\x64\x65viceID\x18\x01 \x02(\t\x12\x11\n\tmessageID\x18\x02 \x02(\t\x12#\n\x12identificationPack\x18\x03 \x01(\x0b\x32\x07.IDPack\x12$\n\x08provider\x18\x04 \x01(\x0e\x32\x12.SatelliteProvider\x12\x1f\n\x08position\x18\x05 \x03(\x0b\x32\r.PositionInfo\x12\x15\n\x03ios\x18\x06 \x01(\x0b\x32\x08.IOsInfo\x12\x19\n\x05\x66lags\x18\x07 \x01(\x0b\x32\n.FlagsInfo\x12!\n\ttelemetry\x18\x08 \x01(\x0b\x32\x0e.TelemetryInfo\x12\x14\n\x0csentDateTime\x18\t \x01(\x04\x12\x18\n\x10receivedDateTime\x18\n \x01(\x04\x12\x11\n\taccountID\x18\x0b \x01(\t\x12\x14\n\x0csubAccountID\x18\x0c \x01(\t\x12\x15\n\x03gps\x18\r \x01(\x0b\x32\x08.GpsInfo\x12\x17\n\x06\x65vents\x18\x0e \x01(\x0b\x32\x07.Events\x12\x10\n\x08openData\x18\x0f \x01(\x0c\x12\x17\n\x04user\x18\x10 \x03(\x0b\x32\t.UserInfo\x12\x1f\n\x07\x62\x65\x61\x63ons\x18\x11 \x03(\x0b\x32\x0e.ReportBeacons\x12$\n\x0c\x63ustomerData\x18\x80\x01 \x01(\x0b\x32\r.CustomerData*3\n\x11SatelliteProvider\x12\x0e\n\nSP_UNKNOWN\x10\x00\x12\x0e\n\nSP_SKYWAVE\x10\x01\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_satellite_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_SATELLITEPROVIDER']._serialized_start=668
  _globals['_SATELLITEPROVIDER']._serialized_end=719
  _globals['_SATELLITEDATA']._serialized_start=170
  _globals['_SATELLITEDATA']._serialized_end=666
# @@protoc_insertion_point(module_scope)
