# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_file_edit.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_file_edit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import maxpb_filetransfer_pb2 as maxpb__filetransfer__pb2
import maxpb_lora_pb2 as maxpb__lora__pb2
import maxpb_users_pb2 as maxpb__users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15maxpb_file_edit.proto\x1a\x18maxpb_filetransfer.proto\x1a\x10maxpb_lora.proto\x1a\x11maxpb_users.proto\"\x97\x01\n\x08\x46ileEdit\x12\x10\n\x08\x64\x65viceID\x18\x01 \x02(\x04\x12\x11\n\tcommandID\x18\x02 \x02(\x04\x12\x1b\n\x08\x66ileType\x18\x03 \x02(\x0e\x32\t.FileType\x12!\n\x08userEdit\x18\x04 \x01(\x0b\x32\x0f.UserLibrayEdit\x12&\n\x08loraEdit\x18\x05 \x01(\x0b\x32\x14.LoraActionsFileEdit\"\xb2\x01\n\x0e\x46ileEditResult\x12\x10\n\x08\x64\x65viceID\x18\x01 \x02(\x04\x12\x11\n\tcommandID\x18\x02 \x02(\x04\x12\x12\n\naddSuccess\x18\x03 \x01(\r\x12\x0f\n\x07\x61\x64\x64\x46\x61il\x18\x04 \x01(\r\x12\x15\n\rdeleteSuccess\x18\x05 \x01(\r\x12\x12\n\ndeleteFail\x18\x06 \x01(\r\x12\x16\n\x0ereplaceSuccess\x18\x07 \x01(\r\x12\x13\n\x0breplaceFail\x18\x08 \x01(\rB#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_file_edit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_FILEEDIT']._serialized_start=89
  _globals['_FILEEDIT']._serialized_end=240
  _globals['_FILEEDITRESULT']._serialized_start=243
  _globals['_FILEEDITRESULT']._serialized_end=421
# @@protoc_insertion_point(module_scope)
