# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_interfaces.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_interfaces.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16maxpb_interfaces.proto\"\x9e\x02\n\x11PeripheralsConfig\x12/\n\x18primarySerialChannelBaud\x18\x01 \x01(\x0e\x32\r.UartBaudrate\x12\x31\n\x1asecondarySerialChannelBaud\x18\x02 \x01(\x0e\x32\r.UartBaudrate\x12$\n\x11primarySerialMode\x18\x03 \x01(\x0e\x32\t.UartMode\x12&\n\x13secondarySerialMode\x18\x04 \x01(\x0e\x32\t.UartMode\x12\x30\n\x19tertiarySerialChannelBaud\x18\x05 \x01(\x0e\x32\r.UartBaudrate\x12%\n\x12tertiarySerialMode\x18\x06 \x01(\x0e\x32\t.UartMode*\xb7\x01\n\nCanBitRate\x12\x0c\n\x08\x43\x42R_NONE\x10\x00\x12\r\n\tCBR_10000\x10\x01\x12\r\n\tCBR_20000\x10\x02\x12\r\n\tCBR_50000\x10\x03\x12\r\n\tCBR_83333\x10\x04\x12\x0e\n\nCBR_100000\x10\x05\x12\x0e\n\nCBR_125000\x10\x06\x12\x0e\n\nCBR_250000\x10\x07\x12\x0e\n\nCBR_500000\x10\x08\x12\x0e\n\nCBR_800000\x10\t\x12\x0f\n\x0b\x43\x42R_1000000\x10\n*\x91\x01\n\x0cUartBaudrate\x12\r\n\tBAUD_9600\x10\x00\x12\x0e\n\nBAUD_19200\x10\x01\x12\x0e\n\nBAUD_38400\x10\x02\x12\x0e\n\nBAUD_57600\x10\x03\x12\x0f\n\x0b\x42\x41UD_115200\x10\x04\x12\x0f\n\x0b\x42\x41UD_230400\x10\x05\x12\x0f\n\x0b\x42\x41UD_460800\x10\x06\x12\x0f\n\x0b\x42\x41UD_921600\x10\x07*\xc7\x01\n\x08UartMode\x12\x14\n\x10UM_MAXPB_CONSOLE\x10\x00\x12\x0f\n\x0bUM_RAW_DATA\x10\x01\x12\x0b\n\x07UM_RFID\x10\x02\x12\x14\n\x10UM_0104_CHECKSUM\x10\x04\x12\x0f\n\x0bUM_DISABLED\x10\x05\x12\x15\n\x11UM_SAT_AT_ORBCOMM\x10\x06\x12\r\n\tUM_RFU_07\x10\x07\x12\r\n\tUM_RFU_08\x10\x08\x12\r\n\tUM_RFU_09\x10\t\x12\r\n\tUM_RFU_10\x10\n\x12\r\n\tUM_RFU_11\x10\x0b\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_interfaces_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_CANBITRATE']._serialized_start=316
  _globals['_CANBITRATE']._serialized_end=499
  _globals['_UARTBAUDRATE']._serialized_start=502
  _globals['_UARTBAUDRATE']._serialized_end=647
  _globals['_UARTMODE']._serialized_start=650
  _globals['_UARTMODE']._serialized_end=849
  _globals['_PERIPHERALSCONFIG']._serialized_start=27
  _globals['_PERIPHERALSCONFIG']._serialized_end=313
# @@protoc_insertion_point(module_scope)
