# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_audio.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11maxpb_audio.proto\"9\n\x13\x41udioIdentification\x12\x0f\n\x07\x61udioID\x18\x01 \x01(\x04\x12\x11\n\taudioPath\x18\x02 \x01(\t\"p\n\x0b\x41udioEvents\x12\x31\n\x13\x61udioIdentification\x18\x01 \x02(\x0b\x32\x14.AudioIdentification\x12\x1c\n\x07\x65ventID\x18\x02 \x02(\x0e\x32\x0b.AudioEvent\x12\x10\n\x08\x64uration\x18\x03 \x01(\r\"U\n\nAudioEntry\x12\x31\n\x13\x61udioIdentification\x18\x01 \x02(\x0b\x32\x14.AudioIdentification\x12\x14\n\x0c\x61udioContent\x18\x02 \x01(\x0c\"$\n\x06\x41udios\x12\x1a\n\x05\x61udio\x18\x01 \x03(\x0b\x32\x0b.AudioEntry\"\xae\x01\n\x0c\x41udioCommand\x12\x10\n\x08\x64\x65viceID\x18\x01 \x02(\x04\x12\x11\n\tcommandID\x18\x02 \x02(\x04\x12&\n\x0b\x63ommandType\x18\x03 \x02(\x0e\x32\x11.AudioCommandType\x12\x31\n\x13\x61udioIdentification\x18\x04 \x03(\x0b\x32\x14.AudioIdentification\x12\x0e\n\x06repeat\x18\x05 \x01(\r\x12\x0e\n\x06volume\x18\x06 \x01(\r\"p\n\nAudiosEdit\x12\x1d\n\x08\x61udioAdd\x18\x01 \x03(\x0b\x32\x0b.AudioEntry\x12!\n\x0c\x61udioReplace\x18\x02 \x03(\x0b\x32\x0b.AudioEntry\x12 \n\x0b\x61udioDelete\x18\x03 \x03(\x0b\x32\x0b.AudioEntry*\xa3\x01\n\nAudioEvent\x12\x0c\n\x08\x41\x45_START\x10\x00\x12\x0b\n\x07\x41\x45_STOP\x10\x01\x12\x0c\n\x08\x41\x45_PAUSE\x10\x02\x12\r\n\tAE_RESUME\x10\x03\x12\r\n\tAE_FINISH\x10\x04\x12\x15\n\x11\x41\x45_FILE_NOT_FOUND\x10\x05\x12\x19\n\x15\x41\x45_UNSUPPORTED_FORMAT\x10\x06\x12\r\n\tAE_RFU_01\x10\x07\x12\r\n\tAE_RFU_02\x10\x08*}\n\x10\x41udioCommandType\x12\x0c\n\x08\x41\x43T_PLAY\x10\x00\x12\x0c\n\x08\x41\x43T_STOP\x10\x01\x12\r\n\tACT_PAUSE\x10\x02\x12\x0e\n\nACT_RESUME\x10\x03\x12\x0e\n\nACT_RFU_03\x10\x04\x12\x0e\n\nACT_RFU_04\x10\x05\x12\x0e\n\nACT_RFU_05\x10\x06\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_AUDIOEVENT']._serialized_start=611
  _globals['_AUDIOEVENT']._serialized_end=774
  _globals['_AUDIOCOMMANDTYPE']._serialized_start=776
  _globals['_AUDIOCOMMANDTYPE']._serialized_end=901
  _globals['_AUDIOIDENTIFICATION']._serialized_start=21
  _globals['_AUDIOIDENTIFICATION']._serialized_end=78
  _globals['_AUDIOEVENTS']._serialized_start=80
  _globals['_AUDIOEVENTS']._serialized_end=192
  _globals['_AUDIOENTRY']._serialized_start=194
  _globals['_AUDIOENTRY']._serialized_end=279
  _globals['_AUDIOS']._serialized_start=281
  _globals['_AUDIOS']._serialized_end=317
  _globals['_AUDIOCOMMAND']._serialized_start=320
  _globals['_AUDIOCOMMAND']._serialized_end=494
  _globals['_AUDIOSEDIT']._serialized_start=496
  _globals['_AUDIOSEDIT']._serialized_end=608
# @@protoc_insertion_point(module_scope)
