# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_journey.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_journey.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13maxpb_journey.proto\"\xb4\x03\n\x07Journey\x12\x11\n\tjourneyID\x18\x01 \x01(\x04\x12\x0e\n\x06userID\x18\x02 \x01(\x04\x12\"\n\x0b\x61\x63tualState\x18\x03 \x01(\x0e\x32\r.JourneyState\x12$\n\rpreviousState\x18\x04 \x01(\x0e\x32\r.JourneyState\x12\x17\n\x0fjourneyInterval\x18\x05 \x01(\r\x12\x19\n\x11operationInterval\x18\x06 \x01(\r\x12 \n\x18loadingUnloadingInterval\x18\x07 \x01(\r\x12\x17\n\x0frestingInterval\x18\x08 \x01(\r\x12\x17\n\x0f\x66\x65\x65\x64ingInterval\x18\t \x01(\r\x12\x1d\n\x15intervalSinceLastRest\x18\n \x01(\r\x12\x1d\n\x15intervalSinceLastFeed\x18\x0b \x01(\r\x12\x1b\n\x13intervalActualState\x18\x0c \x01(\r\x12\x14\n\x0coperationQty\x18\r \x01(\r\x12\x1b\n\x13loadingUnloadingQty\x18\x0e \x01(\r\x12\x12\n\nrestingQty\x18\x0f \x01(\r\x12\x12\n\nfeedingQty\x18\x10 \x01(\r\"Q\n\x0bJourneyInfo\x12\x1f\n\ractualJourney\x18\x01 \x01(\x0b\x32\x08.Journey\x12!\n\x0fpreviousJourney\x18\x02 \x01(\x0b\x32\x08.Journey\"c\n\x0eJourneyCommand\x12\x10\n\x08\x64\x65viceID\x18\x01 \x01(\x04\x12\x11\n\tcommandID\x18\x02 \x01(\x04\x12\x0e\n\x06userID\x18\x03 \x01(\x04\x12\x1c\n\x05state\x18\x04 \x01(\x0e\x32\r.JourneyState*\xa6\x01\n\x0cJourneyState\x12\x15\n\x11JS_OUT_OF_JOURNEY\x10\x00\x12\x13\n\x0fJS_JOURNEY_OPEN\x10\x01\x12\x18\n\x14JS_JOURNEY_OPERATION\x10\x02\x12 \n\x1cJS_JOURNEY_LOADING_UNLOADING\x10\x03\x12\x16\n\x12JS_JOURNEY_RESTING\x10\x04\x12\x16\n\x12JS_JOURNEY_FEEDING\x10\x05\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_journey_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_JOURNEYSTATE']._serialized_start=647
  _globals['_JOURNEYSTATE']._serialized_end=813
  _globals['_JOURNEY']._serialized_start=24
  _globals['_JOURNEY']._serialized_end=460
  _globals['_JOURNEYINFO']._serialized_start=462
  _globals['_JOURNEYINFO']._serialized_end=543
  _globals['_JOURNEYCOMMAND']._serialized_start=545
  _globals['_JOURNEYCOMMAND']._serialized_end=644
# @@protoc_insertion_point(module_scope)
