# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_customer_data.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_customer_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19maxpb_customer_data.proto\"\xe0\x02\n\x0c\x43ustomerData\x12\x12\n\ncustomerId\x18\x01 \x01(\x04\x12\x13\n\x0b\x61greementId\x18\x02 \x01(\x04\x12\x0f\n\x07localId\x18\x03 \x01(\x04\x12\x18\n\x10localEquipmentId\x18\x04 \x01(\x04\x12\x17\n\x0f\x65quipmentItemId\x18\x05 \x01(\x04\x12\x13\n\x0b\x65quipmentId\x18\x06 \x01(\x04\x12\x0f\n\x07groupId\x18\x07 \x01(\x04\x12\x10\n\x08latitude\x18\x08 \x01(\x02\x12\x11\n\tlongitude\x18\t \x01(\x02\x12\x11\n\tcompanyId\x18\n \x01(\x04\x12\x13\n\x0b\x64\x65viceModel\x18\x0b \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x0c \x01(\x04\x12\r\n\x05iccid\x18\r \x01(\t\x12\x0c\n\x04imei\x18\x0e \x01(\x04\x12\x0e\n\x06loraId\x18\x0f \x01(\x04\x12\x12\n\nloraWanEUI\x18\x10 \x01(\x04\x12\x1d\n\x15\x63lone_to_company_list\x18\x11 \x01(\x04\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_customer_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_CUSTOMERDATA']._serialized_start=30
  _globals['_CUSTOMERDATA']._serialized_end=382
# @@protoc_insertion_point(module_scope)
