# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_ioexpander.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_ioexpander.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import maxpb_interfaces_pb2 as maxpb__interfaces__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16maxpb_ioexpander.proto\x1a\x16maxpb_interfaces.proto\"D\n\x10VehicleSignature\x12\x1c\n\x07\x62itRate\x18\x01 \x01(\x0e\x32\x0b.CanBitRate\x12\x12\n\nvehicleKey\x18\x02 \x01(\x0c\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_ioexpander_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_VEHICLESIGNATURE']._serialized_start=50
  _globals['_VEHICLESIGNATURE']._serialized_end=118
# @@protoc_insertion_point(module_scope)
