# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_video.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11maxpb_video.proto*a\n\tHdmiState\x12\x0b\n\x07HS_NONE\x10\x00\x12\x11\n\rHS_DISCONNECT\x10\x01\x12\x18\n\x14HS_CONNECT_NO_SIGNAL\x10\x02\x12\x1a\n\x16HS_CONNECT_WITH_SIGNAL\x10\x03*G\n\x11HdmiOperationType\x12\x14\n\x10HDMI_OPTYPE_NONE\x10\x00\x12\x1c\n\x18HDMI_OPTYPE_SHOW_COCKPIT\x10\x01*\'\n\x12HdmiResolutionType\x12\x11\n\rHDMI_RES_NONE\x10\x00*\"\n\x0fHdmiVideoEvents\x12\x0f\n\x0bHDMIVE_NONE\x10\x00\x42#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_HDMISTATE']._serialized_start=21
  _globals['_HDMISTATE']._serialized_end=118
  _globals['_HDMIOPERATIONTYPE']._serialized_start=120
  _globals['_HDMIOPERATIONTYPE']._serialized_end=191
  _globals['_HDMIRESOLUTIONTYPE']._serialized_start=193
  _globals['_HDMIRESOLUTIONTYPE']._serialized_end=232
  _globals['_HDMIVIDEOEVENTS']._serialized_start=234
  _globals['_HDMIVIDEOEVENTS']._serialized_end=268
# @@protoc_insertion_point(module_scope)
