# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maxpb_global_vars.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'maxpb_global_vars.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17maxpb_global_vars.proto\"\n\n\x08\x43\x64lQueue\"\x0f\n\rCdlItemBuffer\"\n\n\x08RfidItem\"\x0c\n\nGPS_STORED\"\x0f\n\rGSR_ACCVECTOR\"\x0b\n\tDL_FILE_T\"\r\n\x0bOUTPUT_CTRL\"\x0e\n\x0c\x42lackBoxInfoB#\n!com.ceabs.protobuf.proto.maxtrack')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maxpb_global_vars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.ceabs.protobuf.proto.maxtrack'
  _globals['_CDLQUEUE']._serialized_start=27
  _globals['_CDLQUEUE']._serialized_end=37
  _globals['_CDLITEMBUFFER']._serialized_start=39
  _globals['_CDLITEMBUFFER']._serialized_end=54
  _globals['_RFIDITEM']._serialized_start=56
  _globals['_RFIDITEM']._serialized_end=66
  _globals['_GPS_STORED']._serialized_start=68
  _globals['_GPS_STORED']._serialized_end=80
  _globals['_GSR_ACCVECTOR']._serialized_start=82
  _globals['_GSR_ACCVECTOR']._serialized_end=97
  _globals['_DL_FILE_T']._serialized_start=99
  _globals['_DL_FILE_T']._serialized_end=110
  _globals['_OUTPUT_CTRL']._serialized_start=112
  _globals['_OUTPUT_CTRL']._serialized_end=125
  _globals['_BLACKBOXINFO']._serialized_start=127
  _globals['_BLACKBOXINFO']._serialized_end=141
# @@protoc_insertion_point(module_scope)
