# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rev_geo.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'rev_geo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrev_geo.proto\"\xe2\x02\n\x06RevGeo\x12%\n\tresultado\x18\x01 \x02(\x0e\x32\x12.RevGeo.Resultados\x12\x12\n\nlogradouro\x18\x02 \x01(\t\x12\x17\n\x0f\x66\x61ixa_numeracao\x18\x03 \x01(\t\x12\x0b\n\x03\x63\x65p\x18\x04 \x01(\t\x12\x11\n\tmunicipio\x18\x05 \x01(\t\x12\n\n\x02uf\x18\x06 \x01(\t\x12\x0c\n\x04pais\x18\x07 \x01(\t\x12,\n\rpavimentoTipo\x18\x08 \x01(\x0e\x32\x15.RevGeo.PavimentoTipo\x12\x1d\n\x15velocidade_maxima_via\x18\t \x01(\x05\x12\x14\n\x0cmunicipio_id\x18\n \x01(\x05\":\n\nResultados\x12\x0e\n\nENCONTRADO\x10\x00\x12\x12\n\x0eNAO_ENCONTRADO\x10\x01\x12\x08\n\x04\x45RRO\x10\x02\"+\n\rPavimentoTipo\x12\n\n\x06Urbano\x10\x00\x12\x0e\n\nRodoviario\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rev_geo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVGEO']._serialized_start=18
  _globals['_REVGEO']._serialized_end=372
  _globals['_REVGEO_RESULTADOS']._serialized_start=269
  _globals['_REVGEO_RESULTADOS']._serialized_end=327
  _globals['_REVGEO_PAVIMENTOTIPO']._serialized_start=329
  _globals['_REVGEO_PAVIMENTOTIPO']._serialized_end=372
# @@protoc_insertion_point(module_scope)
