# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ultimo_motorista_identificado.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'ultimo_motorista_identificado.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ultimo_motorista_identificado.proto\"\x8f\x04\n\x1bUltimoMotoristaIdentificado\x12\x0e\n\x06serial\x18\x01 \x02(\t\x12\x15\n\ridentificador\x18\x02 \x01(\t\x12\x1a\n\x12\x64\x61ta_identificacao\x18\x03 \x01(\x03\x12\x13\n\x0bmotoristaid\x18\x04 \x01(\x05\x12\x16\n\x0emotorista_nome\x18\x05 \x01(\t\x12\x46\n\x05\x66orma\x18\x06 \x01(\x0e\x32\x37.UltimoMotoristaIdentificado.IdentificacaoCondutorForma\x12T\n\x11idcondutorjornada\x18\x07 \x01(\x0e\x32\x39.UltimoMotoristaIdentificado.IdentificadorCondutorJornada\x12\x11\n\tidcliente\x18\x08 \x01(\t\"g\n\x1aIdentificacaoCondutorForma\x12\x0b\n\x07IBUTTON\x10\x00\x12\x15\n\x11\x43HAVEIRO_WIRELESS\x10\x01\x12\x0f\n\x0b\x43\x41RTAO_RFID\x10\x02\x12\x14\n\x10MOTORISTA_PADRAO\x10\x03\"f\n\x1cIdentificadorCondutorJornada\x12\x14\n\x10NAO_ESPECIFICADO\x10\x00\x12\x12\n\x0eINICIO_JORNADA\x10\x01\x12\x0f\n\x0b\x46IM_JORNADA\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ultimo_motorista_identificado_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ULTIMOMOTORISTAIDENTIFICADO']._serialized_start=40
  _globals['_ULTIMOMOTORISTAIDENTIFICADO']._serialized_end=567
  _globals['_ULTIMOMOTORISTAIDENTIFICADO_IDENTIFICACAOCONDUTORFORMA']._serialized_start=360
  _globals['_ULTIMOMOTORISTAIDENTIFICADO_IDENTIFICACAOCONDUTORFORMA']._serialized_end=463
  _globals['_ULTIMOMOTORISTAIDENTIFICADO_IDENTIFICADORCONDUTORJORNADA']._serialized_start=465
  _globals['_ULTIMOMOTORISTAIDENTIFICADO_IDENTIFICADORCONDUTORJORNADA']._serialized_end=567
# @@protoc_insertion_point(module_scope)
